export const publicationsData = [
  {
    year: 2024,
    type: "Journal",
    title:
      "Distributed denial-of-service attack detection short review: issues, challenges, and recommendations (Accepted)",
    authors: "Habib",
    journal: "",
    volume: "",
    issue: "",
    pages: "",
    doi: "",
    impactFactor: "",
    quartile: "",
  },
  {
    year: 2024,
    type: "Conference",
    title:
      "Review on Wearable Antennas and Circuits: Materials, Designs, Applications and Future Direction (Accepted)",
    authors: "",
    conference: "",
    location: "",
    date: "",
    doi: "",
  },
  {
    year: 2023,
    type: "Journal",
    title:
      "Lithium-ion battery state-of-charge balancing circuit using single resonant converter for electric vehicle applications",
    authors: "Habib, AKM Ahasan, and Mohammad Kamrul Hasan",
    journal: "Journal of Energy Storage",
    volume: 61,
    issue: "",
    pages: "106727",
    doi: "",
    impactFactor: "8.907",
    quartile: "Q1",
  },
  {
    year: 2023,
    type: "Journal",
    title:
      "User privacy prevention model using supervised federated learning‐based block chain approach for internet of Medical Things",
    authors:
      "Dhasarathan, Chandramohan, Mohammad Kamrul Hasan, Shayla Islam, Salwani Abdullah, Shailesh Khapre, Dalbir Singh, Abdulaziz A. Alsulami, and Ali Alqahtani",
    journal: "CAAI Transactions on Intelligence Technology",
    volume: "",
    issue: "",
    pages: "",
    doi: "",
    impactFactor: "5.1",
    quartile: "Q2",
  },
  {
    year: 2023,
    type: "Journal",
    title:
      "Grid-Vehicle-Grid (G2V2G) Efficient Power Transmission: An Overview of Concept, Operations, Benefits, Concerns, and Future Challenges",
    authors:
      "Hossain, Sagar, Md Rokonuzzaman, Kazi Sajedur Rahman, AKM Ahasan Habib, Wen-Shan Tan, Md Mahmud, Shahariar Chowdhury, and Sittiporn Channumsin",
    journal: "Sustainability",
    volume: 15,
    issue: 7,
    pages: "5782",
    doi: "",
    impactFactor: "3.889",
    quartile: "Q2",
  },
  {
    year: 2023,
    type: "Journal",
    title:
      "Lithium-Ion Battery Management System for Electric Vehicles: Constraints, Challenges, and Recommendations",
    authors:
      "Habib, AKM Ahasan, Mohammad Kamrul Hasan, Ghassan F. Issa, Dalbir Singh, Shahnewaz Islam, and Taher M. Ghazal",
    journal: "Batteries",
    volume: 9,
    issue: 3,
    pages: "152",
    doi: "",
    impactFactor: "5.938",
    quartile: "Q2",
  },
  {
    year: 2023,
    type: "Conference",
    title:
      "Electric Vehicle Storage Energy System and Single Charge Balancing Circuit: Preview",
    authors: "Habib, Ahasan, and Sagar Hossain",
    conference: "",
    location: "",
    date: "",
    doi: "",
  },
  {
    year: 2022,
    type: "Journal",
    title:
      "Voltage equalization circuit for retired batteries for energy storage applications",
    authors:
      "Habib, AKM Ahasan, Mohammad Kamrul Hasan, Shayla Islam, Musse Mohamed Ahmed, Azana Hafizah Mohd Aman, Ashish Bagwari, and Sheroz Khan",
    journal: "Energy Reports",
    volume: 8,
    issue: "",
    pages: "367-374",
    doi: "",
    impactFactor: "6.870",
    quartile: "Q1",
  },
  {
    year: 2021,
    type: "Journal",
    title:
      "A review: Energy storage system and balancing circuits for electric vehicle application",
    authors:
      "Habib, AKM Ahasan, Mohammad Kamrul Hasan, Md Mahmud, S. M. A. Motakabber, Muhammad I. Ibrahimya, and Shayla Islam",
    journal: "IET Power Electronics",
    volume: 14,
    issue: 1,
    pages: "1-13",
    doi: "",
    impactFactor: "2.641",
    quartile: "Q2",
  },
  {
    year: 2021,
    type: "Journal",
    title:
      "Review of electric vehicle energy storage and management system: Standards, issues, and challenges",
    authors:
      "Hasan, Mohammad Kamrul, Md Mahmud, AKM Ahasan Habib, S. M. A. Motakabber, and Shayla Islam",
    journal: "Journal of Energy Storage",
    volume: 41,
    issue: "",
    pages: "102940",
    doi: "",
    impactFactor: "6.583",
    quartile: "Q1",
  },
  {
    year: 2020,
    type: "Journal",
    title: "Resonant energy carrier base active charge-balancing algorithm",
    authors:
      "Hasan, Mohammad Kamrul, AKM Ahasan Habib, Shayla Islam, Ahmad Tarmizi Abdul Ghani, and Eklas Hossain",
    journal: "Electronics",
    volume: 9,
    issue: 12,
    pages: "2166",
    doi: "",
    impactFactor: "2.397",
    quartile: "Q3",
  },
  {
    year: 2020,
    type: "Journal",
    title:
      "Active voltage balancing circuit using single switched‐capacitor and series LC resonant energy carrier",
    authors:
      "Ahasan Habib, A. K. M., S. M. A. Motakabber, Muhammad I. Ibrahimy, and Mohammad Kamrul Hasan",
    journal: "Electronics Letters",
    volume: 56,
    issue: 20,
    pages: "1036-1039",
    doi: "",
    impactFactor: "1.316",
    quartile: "Q3",
  },
  {
    year: 2020,
    type: "Journal",
    title:
      "Active cell balancing of Li-Ion batteries using single capacitor and single LC series resonant circuit",
    authors:
      "Azad, Ferdous S., AKM Ahasan Habib, Abidur Rahman, and Istiak Ahmed",
    journal: "Bulletin of Electrical Engineering and Informatics",
    volume: 9,
    issue: 4,
    pages: "1318-1325",
    doi: "",
    impactFactor: "",
    quartile: "Scopus index",
  },
];
